apiVersion: v1
kind: Service
metadata:
  name: beee-imaid
  labels:
    app: imaid
    component: microservice
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: imaid
  sessionAffinity: None
  type: ClusterIP